[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.steps]
setup = "cd backend && npm install"
build = "cd backend && npm run build"
copy = "cp -r backend/prisma ./prisma" 